### ISSUE TITLE
Can't import : "Too many line continuations"

### ISSUE THREAD

**Issue by BSNCH34** [altairwei/ZoteroLinkCitation#1]
Hi,
When right-clicking on "normal" and trying to import the file, here's the error i'm gettting : 

![image](https://github.com/altairwei/ZoteroLinkCitation/assets/169469718/8a1dbd2e-2f6e-420f-892c-e48982a037de)

Can't do anything else, it won't import the file. 

Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit 

Thanks a lot

**Comment by altairwei** [comment]
How do you download [ZoteroLinkCitation.bas](https://github.com/altairwei/ZoteroLinkCitation/blob/master/ZoteroLinkCitation.bas) file? Copy & Paste?

**Comment by altairwei** [comment]
Please open the bas file with any code editor and check if the file encoding is UTF-8 and if the line breaks are CRLF.

**Comment by BSNCH34** [comment]
I downloaded thru the readme (right click > save link) then moved it to another folder.

Re-downloaded thru the download raw tab in github, directly into the folder this time and i've been able to succesfully import it into word !

Rapidly tried it on a dummy file, it seems to work OK so far. (it only make the year "clickable", no the whole citation, but that's not a major concern)

Thanks for the assistance.

**Comment by altairwei** [comment]
> it only make the year "clickable"

This default behaviour can be changed, see [README](https://github.com/altairwei/ZoteroLinkCitation/tree/master?tab=readme-ov-file#author-year-styles).
