### ISSUE TITLE
failure of processing citations because of an error

### ISSUE THREAD

**Issue by qitachenguang** [altairwei/ZoteroLinkCitation#2]
Hi,
When using Elsevier - Harvard (with titles), here's the error i'm gettting :
<img width="266" alt="2978e3f0c92712084ce58dfe43b919d" src="https://github.com/altairwei/ZoteroLinkCitation/assets/113616629/733db4c0-6e78-4f3d-a7dd-591eb232b593">
<img width="268" alt="411045856c7cda541715115934847e7" src="https://github.com/altairwei/ZoteroLinkCitation/assets/113616629/ebb6c71c-996f-4fa1-b13d-dd0cc3c0391f">
<img width="102" alt="cf9351524f75bad740656e0eb629f6c" src="https://github.com/altairwei/ZoteroLinkCitation/assets/113616629/e342cae6-4041-471c-9ba2-e54a2d963be2"> 
neither could IEEE work, and it meets the same error.😵‍💫

**Comment by altairwei** [comment]
Try not to enter any text in the dialogue box that says "Set a style for linked citations".

**Comment by altairwei** [comment]
> <img alt="2978e3f0c92712084ce58dfe43b919d" width="266" src="https://private-user-images.githubusercontent.com/113616629/329918503-733db4c0-6e78-4f3d-a7dd-591eb232b593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE1NDcsIm5iZiI6MTcxNTU4MTI0NywicGF0aCI6Ii8xMTM2MTY2MjkvMzI5OTE4NTAzLTczM2RiNGMwLTZlNzgtNGYzZC1hN2RkLTU5MWViMjMyYjU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjIwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2FmNWNiNDI0OGMyZmIyNGQ5ZWFjZGJkY2M5MGQ4M2YyZmE5NTI2ZDFhNjdkY2Y0MDU0NTU3YmI3NGEyOTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q9Q3-tRywlUVZ4VRZ9lvMtN9bmXyIl-UAJfBhzOPhJs">

This dialog is designed to set an MS Word style to change the text appearance of hyperlinks, such as color, size, font, etc. The Zotero citation style is automatically detected in the document and do not need to be specified.

**Comment by qitachenguang** [comment]
ohh, it works. Thanks~
