### ISSUE TITLE
Error: Subscript out of range

### ISSUE THREAD

**Issue by momiji-oroshi** [altairwei/ZoteroLinkCitation#3]
Hi thanks for this macro but it does not work for my document with th error saying Subscript out of range. I am using this for a about 300-page document and maybe that is the reason?

**Comment by momiji-oroshi** [comment]
Just to clarify, I think its the similar error to the one posted earlier but for me not putting anything in the "Set a style for linked citations" dialog didnt really help. I actuallyu got the syntax error when I first imported your macro so removed the very first line starting with Attribute... I'm a beginner to the macros and may be asking a stupid question but would be appreciated if you could help!

**Comment by altairwei** [comment]
> I actuallyu got the syntax error when I first imported your macro so removed the very first line starting with Attribute...

Can you elaborate on this (preferably with screenshots)? It's possible that having done so, the script functionality has been broken.

**Comment by altairwei** [comment]
Also, please clarify the citation style used and then run the script in debug mode. See exactly which citation is causing the script to crash?

**Comment by momiji-oroshi** [comment]
Thanks for your help!

![error1](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/5e30f743-6754-4bea-9933-07adce570072)
I got this error so removed first line.
![error2](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/d97b07ae-0e54-492a-afdd-0cd7215a4354)
Somehow it allow me to proceed.
![error3](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/670028a2-a39a-4d24-94fc-df5a71b1503a)
I just press okay for this and 
![error4](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/a40803c7-c8e6-4ba5-bff0-5e5226338510)
Got this error.

I am using APA 7th.

**Comment by altairwei** [comment]
Can you tell me the exact version of MS Word you are using? It looks like you are running the script in an older version of MS Word.

**Comment by altairwei** [comment]
> ![error1](https://private-user-images.githubusercontent.com/81696734/339731597-5e30f743-6754-4bea-9933-07adce570072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjE3NzIsIm5iZiI6MTcxODM2MTQ3MiwicGF0aCI6Ii84MTY5NjczNC8zMzk3MzE1OTctNWUzMGY3NDMtNjc1NC00YmVhLTk5MzMtMDdhZGNlNTcwMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwMzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjZlYmY5ZTcwM2E4N2EwMDk2ZTAxNTE3NGRmYjlhMDUxNGNiZWYzZTNmY2UwYWM5ZWJiODBlMDZhNzE2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBrlWcWDcLrltTAmBvSd6z7u7fQMH3YRe1n56tvZ6D8)

This problem is caused by the fact that you are creating a new macro by copying a copy. You can avoid this problem by downloading the script and pouring it in.

**Comment by altairwei** [comment]
I updated the `ZoteroLinkCitation.bas` script to allow you to jump to the source code if you encounter a crash. Can you run this new script once and send me a screenshot of the source code that error occurs on?

**Comment by momiji-oroshi** [comment]
I previously tried downloading the bas file and imported following your guide but got the same error actually.
I tried again by downloading the new file and got this error now.
![Screenshot 2024-06-14 121221](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/f9ea1c90-2919-4a1f-8a67-a32d7fcdf639)
![Screenshot 2024-06-14 121251](https://github.com/altairwei/ZoteroLinkCitation/assets/81696734/ae2be6a5-7caf-4516-8c5e-17ecf850dc5b)

**Comment by altairwei** [comment]
Can you remove any sensitive information and create a minimal Word document for debugging? I'd like to debug the problem you're having locally.

**Comment by momiji-oroshi** [comment]
Hey I kinda solved this by myself - the problem was caused by 1) previously created hyperlinks and 2) modified link (especially not using the blakets). I removed everything before I use your macro and worked like a charm. Thanks again for your work!
